apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ $.Release.Namespace  }}
  labels:
    app: {{ .Values.appName }}
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 3
spec:
  selector:
    matchLabels:
      run: {{ .Values.appName }}
      app: {{ .Values.appName }}
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: {{ .Values.appName }}
        app: {{ .Values.appName }}
        imageTag: "v1.0.1"
    spec:
      serviceAccountName: "{{ .Values.appName }}-service-role"
      terminationGracePeriodSeconds: 60
      containers:
        - name: {{ .Values.appName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.service.containerPort }}
              protocol: TCP
          resources:
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
          volumeMounts:
            - mountPath: "/mnt/wordpress"
              name: creds-volume
              readOnly: true
            - name: wordpress-persistent-storage
              mountPath: /var/www/html
          {{- with .Values.environments }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
    {{ if hasKey .Values "tolerations" }}
    {{- with .Values.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
    {{- end }}
    {{ end }}
      {{ if hasKey .Values "nodeSelector" }}
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim
      - name: creds-volume
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
              secretProviderClass: aws-secrets2
      nodeSelector:
      {{ with .nodeSelector }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{ end }}
    