apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  namespace: {{ $.Release.Namespace  }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.sc.name }} 
  resources:
{{ toYaml .Values.sc.resources | indent 12 }}