apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets2
  namespace: {{ $.Release.Namespace }}
spec:
  provider: aws
  secretObjects:
    - secretName: vr-creds
      type: Opaque
      data:
        - objectName: rds-endpoint
          key: DATABASE_HOST_STRING_Secret
        - objectName: rds-password
          key: DB_PASSWORD_Secret
        - objectName: rds-user
          key: DB_USER_NAME_Secret
        - objectName: rds-name
          key: DATABASE_NAME_Secret
  parameters:
    objects: |
        - objectName: "/{{ $.Release.Namespace }}/RDS/ENDPOINT"
          objectType: "ssmparameter"
          objectAlias: rds-endpoint
        - objectName: "/{{ $.Release.Namespace }}/RDS/PASSWORD"
          objectType: "ssmparameter"
          objectAlias: rds-password
        - objectName: "/{{ $.Release.Namespace }}/RDS/USER"
          objectType: "ssmparameter"
          objectAlias: rds-user
        - objectName: "/{{ $.Release.Namespace }}/RDS/NAME"
          objectType: "ssmparameter"
          objectAlias: rds-name