apiVersion: v1
kind: Service
metadata:
  labels:
    app: wordpress
    tier: frontend
  name: "svc-{{ .Values.appName }}"
  namespace: "{{ $.Release.Namespace }}"
spec:
    ports:
        -   name: www
            port: 80
            protocol: TCP
            targetPort: {{ .Values.service.containerPort }}
    selector:
        run: {{ .Values.appName }}
    type: ClusterIP